### ISSUE TITLE
Refuses to take a text/plain content, expecting text/plain; charset=utf-8

### ISSUE THREAD

**Issue by zoffixznet** [Raku/whateverable#17]
```
<Zoffix> committable, 5605d5f http://temp.perl6.party/foo.txt
<committable> Zoffix: It looks like a URL, but mime type is 'text/plain' while I was expecting 'text/plain; charset=utf-8'. I can only understand raw links, sorry.
```

**Comment by AlexDaniel** [comment]
So if it is not ``utf-8``, should it blindly assume that it is ``utf-8``? Or what kind of encoding should it expect?

**Comment by zoffixznet** [comment]
Per [World Wide Web Consortium](https://www.w3.org/International/articles/http-charset/index):

> HTTP 1.1 says that the default charset is ISO-8859-1. But there are too many unlabeled documents in other encodings, so browsers use the reader's preferred encoding when there is no explicit charset parameter.

IMO, for this particular purpose, assuming UTF-8 when nothing is specified is a good default.

**Comment by jonathanstowe** [comment]
Somewhere I've done "try utf-8 and if that fails do iso-8859-1" which always seems like a reasonable compromise (though may be more effort than warranted in the circumstance,)

**Comment by MasterDuke17** [comment]
I'm in favor of trying anything with a mime type that contains 'perl' or 'text', and defaulting to utf-8 seems reasonable.

**Comment by MasterDuke17** [comment]
Luckily enough, same as before!

**Comment by AlexDaniel** [comment]
more specifically it will default to utf-8. OK.

**Comment by AlexDaniel** [comment]
I want to write a test for this, but is there any link that will be reliably giving a page with ``text/plain`` till the end of our days?

**Comment by zoffixznet** [comment]
Something on http://httpbin.org/ ? Didn't see an option to generate custom content-type when I skimmed the page though

**Comment by AlexDaniel** [comment]
@JJ does it really test it though? I think github correctly sets utf-8 so this has never been an issue with github.
