### ISSUE TITLE
Use MVM_SPESH_BLOCKING

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/whateverable#198]
See https://6guts.wordpress.com/2017/08/06/moarvm-specializer-improvements-part-1-gathering-data/

> When I first mentioned moving specialization work off to its own thread on #moarvm, brrt (who leads development of the JIT) was immediately concerned about the unpredictability this would introduce. Threads are scheduled a bit differently between runs, which would make it a nightmare to reproduce and hunt down specializer and JIT compiler bugs, **including using the bisection approach to work out exactly which specialization made things go wrong**. It was an excellent point.
>
> Therefore, I introduced the **MVM_SPESH_BLOCKING** environment variable. When set, a thread executing code will send off its log, and then block until the spesh worker thread has finished processing it and installing specializations. This means that, for a single threaded program, the behavior will again be fully deterministic.

**Comment by jnthn** [comment]
fiww, I'd agree that if doing a bisect for bugs this makes a lot of sense. If doing a bisect for a performance difference, less so perhaps (especially for short-lived things like startup, where the fact that we get on with the optimization work in the background while still working on the original program, and maybe exit before the opts are done, is a feature).

**Comment by AlexDaniel** [comment]
@jnthn thanks for following this repo and for your input!

I don't think people use bisectable to find performance changes (at least, they should not). Benchable is a better tool for this, and there are [plans to make it even better](https://github.com/perl6/whateverable/issues/189).

In any cases, I've added a [warning](https://github.com/perl6/whateverable/wiki/Bisectable) to the documentation to suggest Benchable for this use case.

**Comment by AlexDaniel** [comment]
I think this is a dup of https://github.com/Raku/whateverable/issues/198.
