### ISSUE TITLE
The Mask references and political correctness

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/whateverable#242]
What if someone is:
* [a sergeant](https://github.com/perl6/whateverable/blob/11af308d8d45d5ee095b7fa7d24ee753a9dc85b8/lib/Whateverable.pm6#L81-L82)?
* [a kid](https://github.com/perl6/whateverable/blob/11af308d8d45d5ee095b7fa7d24ee753a9dc85b8/lib/Whateverable.pm6#L72)?
* [a one-armed man](https://github.com/perl6/whateverable/blob/11af308d8d45d5ee095b7fa7d24ee753a9dc85b8/lib/Whateverable.pm6#L103)?

Surely there's a chance they might not like these messages?

Does anybody have any better alternatives that are just as funny yet don't refer to things that some people might not like?

Reference: [video](https://www.youtube.com/watch?v=HflILF_9O2k&feature=youtu.be&t=25)

**Comment by zoffixznet** [comment]
> "I'm sorry Dave, I'm afraid I can't do that"

**Comment by moritz** [comment]
[lp0 on fire!](https://en.wikipedia.org/wiki/Lp0_on_fire)

**Comment by AlexDaniel** [comment]
[“418 – I'm a Teapot”](https://httpstatuses.com/418)

**Comment by AlexDaniel** [comment]
> \<timotimo\> AlexDaniel_: i want to nominate "Not the bees!" for whateverable error messages

**Comment by AlexDaniel** [comment]
All of these suggestions are wonderful. Unfortunately, I kinda forgot about this ticket and ended up [changing it](https://github.com/Raku/whateverable/commit/f18c0216a661956358f598b3e5056e8f8cd155df) to something else. I think it's trendy, although I don't fully [understand it](https://en.wikipedia.org/wiki/VSCO_girl) yet :)
