### ISSUE TITLE
Notable losing its db when out of space

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/whateverable#304]
Notable stores notes in a simple json file, which normally works alright except that it just lost the whole file attempting to write it when there was no free space on the server.

Either it should write to a temp file first (and then move that file), or it should use a proper DBMS.

**Comment by JJ** [comment]
Maybe go halfway: use Sqlite.

**Comment by AlexDaniel** [comment]
That's something I'd call a DBMS, yes.
