### ISSUE TITLE
Failing bitrotted tests

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/whateverable#340]
Was doing release prep for rakudo and realized that many whateverable test files no longer pass (although they used to a long time ago). I can't spot any rakudo issues, mostly it's just bitrot in the bots themselves. Most commonly used bots seem to be OK and their tests pass, but other bots need more love.

- [ ] benchable.t
- [x] bisectable.t
- [ ] bloatable.t
- [ ] committable.t
- [ ] coverable.t
- [x] evalable.t
- [ ] greppable.t
- [ ] nativecallable.t
- [x] notable.t
- [ ] quotable.t – requires irc log files which are not public
- [ ] releasable.t – fails due to lack of mocks (it fetches real data which changes all the time)
- [ ] statisfiable.t
- [x] tellable.t
- [x] unicodable.t

**Comment by taboege** [comment]
I also see this on current master from `commitable.t`
```
not ok 108 - “releases” query
# Failed test '“releases” query'
# at /tmp/whateverable-repo/xt/lib/Testable.pm6 (Testable) line 118
# expected: [/^ $($t.our-nick) ‘, ¦releases (’\d+‘ commits): «Perl 6 (6.c)␤»’ $/]
#  matcher: 'infix:<~~>'
#      got: ["testable739686, https://whatever.able/fakeupload"]
# Test failed. Stopping test suite, because PERL6_TEST_DIE_ON_FAIL environmental variable is set to a true value.
# Bot process finished (exit code=0, signal=1)
```

**Comment by AlexDaniel** [comment]
Same as https://github.com/Raku/whateverable/issues/377, this is now a bit outdated.
