### ISSUE TITLE
fails on install with "...Redeclaration of symbol 'Message'...."

### ISSUE THREAD

**Issue by jdv** [Raku/whateverable#387]
root@4c3144b8fb7d:/Blin# zef install --verbose --force-install Whateverable
The following candidates are already installed: Whateverable
===> Searching for: Whateverable
===> Found: Whateverable:ver<1.0.11> [via Zef::Repository::Ecosystems<rea>]
===> Fetching [OK]: Whateverable:ver<1.0.11> to /tmp/.zef/1669180276.5893.4554.310080263431/Whateverable%3Aver%3C1.0.11%3E%3Aauth%3Cgithub%3ARaku%3E.tar.gz
===> Extraction [OK]: Whateverable to /tmp/.zef/Whateverable%3Aver%3C1.0.11%3E%3Aauth%3Cgithub%3ARaku%3E.tar.gz
===> Testing: Whateverable:ver<1.0.11>
===> Testing [OK] for Whateverable:ver<1.0.11>
===> Installing: Whateverable:ver<1.0.11>
===> Install [FAIL] for Whateverable:ver<1.0.11>: ===SORRY!=== Error while compiling /Blin/site#sources/FFCE30B7629EBB9BF4F889999F97C35CAC8EA91C (Whateverable)
Redeclaration of symbol 'Message'.
at /Blin/site#sources/FFCE30B7629EBB9BF4F889999F97C35CAC8EA91C (Whateverable):36
------> constant Message = IRC::Client::Message⏏;

===SORRY!=== Error while compiling /Blin/site#sources/FFCE30B7629EBB9BF4F889999F97C35CAC8EA91C (Whateverable)
Redeclaration of symbol 'Message'.
at /Blin/site#sources/FFCE30B7629EBB9BF4F889999F97C35CAC8EA91C (Whateverable):36
------> constant Message = IRC::Client::Message⏏;

root@4c3144b8fb7d:/Blin# raku -v
Welcome to Rakudo™ v2022.07.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2022.07.
root@4c3144b8fb7d:/Blin#

**Comment by coke** [comment]
Looks like root cause of  https://github.com/Raku/Blin/issues/31

**Comment by lizmat** [comment]
The weird thing is that trying to do the install again, states:
````
% zef install Whateverable --verbose       
The following candidates are already installed: Whateverable
All candidates are currently installed
````

**Comment by lizmat** [comment]
Turns out I already fixed the issue locally in November, but for some reason forgot to bump and release  :-(

**Comment by lizmat** [comment]
https://github.com/Raku/whateverable/commit/9eff36756a is a fix
