### ISSUE TITLE
Make it possible to get stdout separately from stderr

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/whateverable#54]
https://irclog.perlgeek.de/perl6/2016-10-21#i_13439518

**Comment by MasterDuke17** [comment]
Didn't we do this a while ago and then switch back for some?

**Comment by AlexDaniel** [comment]
Yeah, because separate stdout/stderr is not what most expect as a default behavior. Does not mean it should not be possible :)

**Comment by AlexDaniel** [comment]
Has anybody actually needed this? Like, there are certain features that I *actually need*, like #44. But this? Sounds cool but practically useless.

**Comment by AlexDaniel** [comment]
Moreover, you can use `run ‘perl6’, …` and execute any code in any way you like (and you can choose to only use stderr from it). I have never needed this feature but if I ever do I'll just spend a few seconds on writing my own gist and that'd be it.
